### ISSUE TITLE
Off hand

### ISSUE THREAD

**Issue by xXgal4xy** [alvin0319/Offhand#33]
![28C0849A-6DEE-4507-9C0E-60355BEBE67B](https://user-images.githubusercontent.com/84987244/120020030-31c75700-bfb7-11eb-8f80-f1c58b9261c9.jpeg)
Hi yes uh this is xXgal4xy_h7p3rXx on discord it won’t let me use the off hand plugin on bedrock Edition and it’s on and enabled just won’t let me put anything on off hand How do I fix it?

**Comment by alvin0319** [comment]
I need more information

**Comment by alvin0319** [comment]
Not enough information.
