### ISSUE TITLE
Crash on join

### ISSUE THREAD

**Issue by ElectroGamesDev** [alvin0319/Offhand#40]
`[21:16:09] [Server thread/CRITICAL]: InvalidArgumentException: "Cannot remove fixed window 119 (alvin0319\Offhand\PlayerOffhandInventory) from El3ctr0Games" (EXCEPTION) in "pmsrc/src/pocketmine/Player" at line 4145`
I never had anything in my offhand.

**Comment by alvin0319** [comment]
I need more information. please put the backtrace on issue.

**Comment by alvin0319** [comment]
Closing due to no information.

**Comment by ElectroGamesYT** [comment]
> I need more information. please put the backtrace on issue.

What backtrace?

**Comment by ElectroGamesDev** [comment]
> I need more information. please put the backtrace on issue.

Im not sure what the backtrace was, maybe try adding the plugin to your server, leaving and rejoining.

**Comment by alvin0319** [comment]
@ElectroGamesYT Backtrace means full error, All red lines.
