### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xodamcm** [alvin0319/Offhand#41]
Not working i have crash of worldguard with this plugin
 #0 plugins/3347_pe_worldguard.phar/src/MihaiChirculete/WorldGuard/WorldGuard(442): pocketmine\utils\Utils::errorExceptionHandler

**Comment by xodamcm** [comment]
Why do you closed my issue ???

**Comment by alvin0319** [comment]
Not enough information. and I don't care the crash with other plugin.

**Comment by xodamcm** [comment]
Okok

**Comment by xodamcm** [comment]
Thank you for reply
