### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by xodamcm** [alvin0319/Offhand#42]
Make compatibility with VanillaX Plugin

**Comment by alvin0319** [comment]
What is VanillaX plugin

**Comment by xodamcm** [comment]
this plugin add lot’s of things vanilla like enchantment, anvil, brewing stand, firework, elytra, emotes, ALL enchantment (mending, enchant trident, crossbow… all enchant) this plugin add LOT’S OF vanilla things 
You can see this short video
https://m.youtube.com/watch?v=SWCoRNPLJkg
Or github link
https://github.com/CLADevs/VanillaX

I can’t remove this plugin because is very important for my survival server but, if you can make compatibilty with him, this is so nice

**Comment by alvin0319** [comment]
That plugin also has offhand support. if you can't remove just remove my plugin. or ask author to support it since I don't have any mind to support other plugin.
